#!/usr/bin/bash

# Takes about 5-10 minutes

EXIT_SUCCESS=0
EXIT_FAILURE=1

# PROGRAM_NAME=$(echo $0 | tr '/' '\n' | tail -n1)
PROGRAM_NAME=$(basename $0)

FLAG=
BACK_UP_LOCATION=

if [[ $1 =~ "-" ]];then
    FLAG=$1
    BACK_UP_LOCATION=$2
else 
    BACK_UP_LOCATION=$1
    FLAG=$2
fi

BACK_UP_CONFIG_DIR="Dotfiles"


CONFIGS_TO_BACKUP=(
    alacritty awesome bspwm nvim polybar task zsh xfce4/terminal elinks lynx qutebrowser
)
DOCUMENTS_TO_BACKUP=(
    Bin Documents Pictures Notes
    )

backup_configs(){
    for dir in ${CONFIGS_TO_BACKUP[@]};do
        echo "Backing Up $dir"
        sudo rm -rf $BACK_UP_LOCATION/$BACK_UP_CONFIG_DIR 2>/dev/null
        sudo cp -ru ~/.config/$dir $BACK_UP_LOCATION/$BACK_UP_CONFIG_DIR 2>/dev/null
    done
}

# TODO: Make this a list like the configs
backup_documents(){
    for dir in ${DOCUMENTS_TO_BACKUP[@]};do
        echo "Backing Up $dir"
        sudo rm -rf $BACK_UP_LOCATION/$dir 2>/dev/null
        sudo cp -ru ~/$dir $BACK_UP_LOCATION 2>/dev/null
    done

}
# individual_backups(){
#     sudo cp -ru ~/Documents $BACK_UP_LOCATION
# }

print_help_message(){
    echo -e "USAGE      $PROGRAM_NAME [options] target-drive
OPTIONS
    -h      --help              Dislays this message.
    -c      --configs           Backs up only configs specified.
    -d      --documents         Backs up only documents specified.
DEFAULT
    Default option is to backup both Documents and Configs."
}

check_if_drive_is_mounted(){
    echo HELLO
    # if [[ $# -eq 0 ]];then
    #     echo "Too few arguments"
    # fi
    # [[ -z $BACK_UP_LOCATION ]] && echo "TRUE"

    # [[ -d $BACK_UP_LOCATION/$BACK_UP_CONFIG_DIR ]]
    # [[ $? -ne 0 ]] && echo "Your external drive might not be mounted." && exit $EXIT_FAILURE
}
backup_files(){
    echo $FLAG
    echo $BACK_UP_LOCATION

    # check_if_drive_is_mounted()

    # case $FLAG in
    #     -c | --configs)
    #         # check_if_drive_is_mounted
    #         backup_configs
    #         exit 0
    #         ;;
    #     -d | documents)
    #         # check_if_drive_is_mounted
    #         backup_documents
    #         exit 0
    #         ;;

    #     -h | --help)
    #         print_help_message
    #         exit 0
    #         ;;

    #     "")
    #         # check_if_drive_is_mounted
    #         backup_configs
    #         backup_documents
    #         exit 0
    #         ;;
    #     esac
    # exit 1
}

backup_files
