#!/usr/bin/bash

# When first ran, it might not run your program after compiling
# Just run it again
executable=`find build -maxdepth 1 -type f`
cmake -S . -B build && make -C build
for value in $executable
do
    if [[ -x $value ]];then
        ./$value
    fi
done
