#!/usr/bin/bash

# When first ran, it might not run your program after compiling
# Just run it again
FLAG=$1
EXIT_SUCCESS=1
PROGRAM_NAME=$(echo $0 | tr '/' '\n' | tail -n1)

cpp_run (){
    cpp-run-help
    executable=`find build -maxdepth 1 -type f`
    cmake -S . -B build -Werror=dev && make -C build
    for value in $executable
    do
        if [[ -x $value ]];then
            ./$value
        fi
    done

    exit $EXIT_SUCCESS
}
cpp-run-help(){
    case $FLAG in
        -h | --help)
    echo -e "USE
\tRun \"${PROGRAM_NAME}\" without any options wherever your CMake file is located.
DESCRIPTION
\tA simple script that runs cmake and make, then executes your program."
            exit $EXIT_SUCCESS
    esac
}

cpp_run
