#!/usr/bin/bash

# -------------------------------------------------------------
# A program that checks the last time you updated your system. 
# -------------------------------------------------------------

SUCCESS=0
EXIT_SUCCESS=0
EXIT_FAILURE=1
FLAG=$1

PROGRAM_NAME=$(echo $0 | tr '/' '\n' | tail -n1)

#TODO: Figure out what the equivalent package for "dateutils"
# is for arch linux

function run() 
{
    distro=$(uname -n)
    case ${distro} in 
        "fedora")  last_fedora_up_grade_date;;
        "arch" ) last-system-update && break || 
            echo "ERROR: FAILED TO IDENTIFY DISTRO" && break;;
        *)
            break;;
    esac
}

last_fedora_up_grade_date() 
{
    last_upgrade=$(dnf history | grep upgrade | tr -s ' ' | cut -d'|' -f 3 | cut -d' ' -f 2 | head -n 1)
    last_update=$(dnf history | grep update | tr -s ' ' | cut -d'|' -f 3 | cut -d' ' -f 2 | head -n 1)
    last_uu=${last_upgrade:-${last_update}}
    today=$(date +"%Y-%m-%d")

    echo $(datediff ${last_uu} ${today}) Days
}

last-system-update(){
    last-system-update-help
    get-last-update
}


get-last-update(){
    cat /var/log/pacman.log | \
        grep -i "system upgrade" | cut -d'[' -f2 | \
        cut -d']' -f1 | cut -d'-' -f1-3 | tr "T" " " | \
        tail -n1

    return $SUCCESS
}

last-system-update-help(){
help_text="USE\n
\tRun $PROGRAM_NAME without any options or arguments\n
DESCRIPTION\n
\tTells you the date and time of the last time you ran a system update."
    case $FLAG in
        -h | --help)
            exit $EXIT_FAILURE;;
    esac
}
# last-system-update
run
