#!/usr/bin/bash
# A function that prints the current ram use to console until stopped
FLAG=$1
ram-used (){
    case $FLAG in
        -h | --help)
            echo -e "DESCRIPTION"
            echo -e "\tA simple tool to tell you how much ram you are using"
            exit 1;;
    esac
    while [[ 1 ]];do
        clear
        free -h | tr -s ' ' | cut -d' ' -f3 | head -n2
        sleep 1.5
    done
}
ram-used
