#!/usr/bin/bash
# A function that prints the current ram use to console until stopped
FLAG=$1
PROGRAM_NAME=$(echo $0 | tr '/' '\n' | tail -n1)
EXIT_SUCCESS=1
ram-used (){
    ram-used-help
    while [[ 1 ]];do
        clear
        free -h | tr -s ' ' | cut -d' ' -f3 | head -n2
        sleep 1.5
    done
    exit $EXIT_SUCCESS
}

ram-used-help(){
    case $FLAG in
        -h | --help)
            echo -e "USE
\tRun $PROGRAM_NAME without any options or flags.
DESCRIPTION
\tA simple tool to tell you how much ram you are using"
            exit $EXIT_SUCCESS;;
    esac

}

ram-used
