#!/usr/bin/bash

language=$1
practice_directory=~/Notes/Computers/Coding/Coding-Languages

if [[ $language == "" ]];then
    echo "Err: No argument entered"
    exit 1
fi
case $language in
    asm | assembly)
        cd $practice_directory/Assembly/basics/scratch/
        nvim main.asm;;
    c)
        cd $practice_directory/C/scratch
        nvim src/branch.c;;
    cpp)
        cd $practice_directory/Cpp/scratch/
        nvim src/branch.cpp;;
    js | javascript)
        cd $practice_directory/Javascript/scratch
        nvim main.js;;
    py | python)
        # I chose to cd to the directory so that you could add files delete files more easily
        cd $practice_directory/Python/scratch
        nvim src/scratch.py;;
    rs | rust)
        cd $practice_directory/Rust/scratch
        nvim src/main.rs;;
    scala)
        cd $practice_directory/Scala/Basics/scratch
        nvim src/main/scala/Main.scala;;
    sh | bash)
        cd $practice_directory/Bash-Scripting/scratch
        nvim main.sh;;
    *)
        echo "Err: $language is not a valid entry";;
esac




