#!/usr/bin/bash

PROGRAM_NAME=$(echo $0 | tr '/' '\n' | tail -n1)
EXIT_SUCCESS=0
EXIT_FAILURE=1
FLAG=$1
language=$1
practice_directory=~/Notes/Computers/Coding/Coding-Languages

scratch-pad(){
    scratch-pad-help
    # If no language is specified, exit
    [[ $language == "" ]] && echo "Err: No argument entered" && exit $EXIT_FAILURE

    case $language in
        asm | assembly)
            cd $practice_directory/Assembly/basics/scratch/
            nvim main.asm;;
        c)
            cd $practice_directory/C/scratch
            nvim src/branch.c;;
        cpp)
            cd $practice_directory/Cpp/scratch/
            nvim src/branch.cpp;;
        js | javascript)
            cd $practice_directory/Javascript/scratch
            nvim main.js;;
        py | python)
            # I chose to cd to the directory so that you could add files delete files more easily
            cd $practice_directory/Python/scratch
            nvim src/scratch.py;;
        rs | rust)
            cd $practice_directory/Rust/scratch
            nvim src/main.rs;;
        scala)
            cd $practice_directory/Scala/scratch
            nvim src/main/scala/Main.scala;;
        sh | bash)
            cd $practice_directory/Bash-Scripting/scratch
            nvim main.sh;;
        *)
            echo "Err: $language is not a valid entry"
            exit $EXIT_FAILURE;;
    esac
    exit $EXIT_SUCCESS
}

scratch-pad-help(){
    case $FLAG in
        -h | --help)
            echo -e "USE
\tscratch-pad [arg]
DESCRIPTION
\tA script that takes you to an empty template of your desired language.
SUPPORTED ARGS
\tassembly, bash, c, cpp, javascript, python, rust, scala"
            exit $EXIT_SUCCESS;;
    esac
}

scratch-pad



