#!/usr/bin/bash

PROGRAM_NAME=$(echo $0 | tr '/' '\n' | tail -n1)
EXIT_SUCCESS=0
EXIT_FAILURE=1
FLAG=$1
language=$1
practice_directory=/tmp/code/${language}
valid_langs=(asm c cpp java js py rs scala)

scratch-pad()
{
    scratch-pad-help
    # If no language is specified, exit
    [[ ${language} == "" ]] && echo "Err: No argument entered" && exit $EXIT_FAILURE

    for lang in ${valid_langs[@]}
    do 
        if [[ $lang == ${language} ]];then
            cd_in_cd_back ${practice_directory}/main.${language}
            exit ${EXIT_SUCCESS}
        fi
    done

    echo "Err: $language is not a valid entry"
    exit ${EXIT_FAILURE}
}

cd_in_cd_back()
{
    [[ -d ${practice_directory} ]] || mkdir -p ${practice_directory}
    cd ${practice_directory}
    nvim $1
    cd -
}

scratch-pad-help()
{
    case $FLAG in
        -h | --help)
            echo -e "USE
    scratch-pad [arg]
DESCRIPTION
    A script that takes you to an empty template of your desired language.
SUPPORTED ARGS
    asm, bash, c, cpp, java, js, py, rs, scala"
            exit $EXIT_SUCCESS;;
    esac
}

scratch-pad
