#!/usr/bin/bash

SEARCH_TERM=$1
NARROW_SEARCH=^${SEARCH_TERM}
FLAG=$2 
EXIT_SUCCESS=0
PROGRAM_NAME=$(echo $0 | tr "/" '\n' | tail -n1)
search-man (){
    search-man-help
    case $FLAG in
        -b)  # Broad Search
            man -k $SEARCH_TERM | grep -w $SEARCH_TERM --color;;
        -B) # VERY BROAD
            man -k $SEARCH_TERM | grep $SEARCH_TERM --color;;
        *) # Default is a narrow search
            man -k $SEARCH_TERM | grep -w $NARROW_SEARCH --color;;
    esac

    exit $EXIT_SUCCESS
}


search-man-help(){
    case $SEARCH_TERM in
        -h | --help)
        echo -e "USE
\t$PROGRAM_NAME [search_term] [options]

DESCRIPTION
\tProvides a more refined result when searching the man pages
OPTIONS
\t-b\tBroad search
\t-B\tVery Broad Search
DEFAULT OPTION
\tNarrow Search is set by default"
        exit $EXIT_SUCCESS;;
    esac
}
search-man
