#!/usr/bin/bash

# A script Searches the web from your terminal using Elinks

PROGRAM_NAME=$(basename $0)
# CHANGE YOUR DEFAULT CONFIG DIR HERE
APP="elinks"
ELINKS_CONFIG_DIR=~/.config/elinks
ELINKS=$(echo elinks -config-dir $ELINKS_CONFIG_DIR)
OTTER_BROWSER="otter-browser"


EXIT_SUCCESS=0
EXIT_FAILURE=1

ARGS=$@
ARGS_IF_FLAG=""
FLAG=$1
ARG_1=$1

SEARCH_TERMS=$(echo $ARGS | tr ' ' '+')
SEARCH_ENGINE="duckduckgo.com/lite"
SEARCH_LINGO="/?q="

YELLOW='\033[1;33m'
RED='\031[1;33m'
NO_COLOR='\033[0m'



elinks_search(){
    check_flags                      # Check if they entered any flags
    check_is_url_search              # Check if they entered in a URL
    search_url=$SEARCH_ENGINE$SEARCH_LINGO$SEARCH_TERMS 
    case $APP in 
        elinks)
            # elinks update causes -config-dir to thow error
            $ELINKS $search_url 2>/dev/null               # Else assume it's a general search
            exit $EXIT_SUCCESS;;
        otter)
            # elinks update causes -config-dir to thow error
            $($OTTER_BROWSER "$search_url") 2>/dev/null &
            exit $EXIT_SUCCESS;;
    esac

}

check_is_url_search(){
    # If there is a period in the flag, then they probably entered a URL
    [[ $FLAG =~ "." ]] && $ELINKS $ARG_1 && exit $EXIT_SUCCESS
}

display_help_message(){
            echo -e "USAGE
    ${YELLOW}$PROGRAM_NAME${NO_COLOR} [options] [website-url]
    ${YELLOW}$PROGRAM_NAME${NO_COLOR} [options] [text-to-search]
DESCRIPTION
    Searches the web from your terminal using Elinks
OPTIONS
    No Args is equivalent to running \"elinks\"
    --help      -h      Shows this message and quits
    --bing      -b      Use Google's Search Engine (Default = Duckduckgo)
    --google    -g      Use Google's Search Engine (Default = Duckduckgo)
    --otter     -o      Use Otter Browser (Light-weight GUI) with Duckduckgo
EXAMPLES
    ${YELLOW}$PROGRAM_NAME${NO_COLOR} stackoverflow.com 
    ${YELLOW}$PROGRAM_NAME${NO_COLOR} how big is the moon
    ${YELLOW}$PROGRAM_NAME${NO_COLOR} --google what does sand look like"
}
check_flags() {
    case $FLAG in
        -h | --help)
            display_help_message
        exit $EXIT_SUCCESS
        ;;

    -g | --google)
        ARGS=${ARGS[@]:1}
        SEARCH_ENGINE="google.com"
        SEARCH_LINGO="/search?q="
        ;;
    -b | --bing)
        ARGS=${ARGS[@]:1}
        SEARCH_ENGINE="bing.com"
        SEARCH_LINGO="/search?q="
        ;;
    -o | --otter)
        ARGS=${ARGS[@]:1}
        APP="otter"
        ;;

    "") 
        $ELINKS
        exit $EXIT_SUCCESS
        ;;

    -*) # If they enter any other command, then display the help message
        echo -e "${RED}Err: Invalid Option ($FLAG)${NO_COLOR}"
        display_help_message
        exit $EXIT_FAILURE
        ;;

    esac
}

elinks_search
