#!/usr/bin/bash

# Pushes a whole directory to my server

LOCAL_DIR=$1

SERVER_ADDRESS=$(echo $SERVER_ADDRESS)
SERVER_HOSTNAME=$(echo $SERVER_HOST)
SERVER_PORT=$(echo $SERVER_PORT)


help_message()
{
    echo -e "\
USAGE
    $(basename $0) dirname
DESCRIPTION
    Will push a directory ~/external-drive on your server.

OPTIONS
    -h --help   displays this message."

    return
}
case $LOCAL_DIR in
    -h | --help)
        help_message
        exit 0
        ;;
    "")
        help_message
        exit 0
        ;;
esac
rsync --delete -Pre "ssh -p $SERVER_PORT" $LOCAL_DIR $SERVER_ADDRESS:/home/$SERVER_HOSTNAME/external-drive/$LOCAL_DIR



